// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: memory_manager.proto

#include "memory_manager.pb.h"
#include "memory_manager.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace memory_manager {

static const char* MemoryManagerService_method_names[] = {
  "/memory_manager.MemoryManagerService/Create",
  "/memory_manager.MemoryManagerService/IncreaseRefCount",
  "/memory_manager.MemoryManagerService/DecreaseRefCount",
  "/memory_manager.MemoryManagerService/Set",
  "/memory_manager.MemoryManagerService/Get",
};

std::unique_ptr< MemoryManagerService::Stub> MemoryManagerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MemoryManagerService::Stub> stub(new MemoryManagerService::Stub(channel, options));
  return stub;
}

MemoryManagerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Create_(MemoryManagerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_IncreaseRefCount_(MemoryManagerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DecreaseRefCount_(MemoryManagerService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(MemoryManagerService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(MemoryManagerService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MemoryManagerService::Stub::Create(::grpc::ClientContext* context, const ::memory_manager::AllocateRequest& request, ::memory_manager::AllocateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::AllocateRequest, ::memory_manager::AllocateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Create_, context, request, response);
}

void MemoryManagerService::Stub::async::Create(::grpc::ClientContext* context, const ::memory_manager::AllocateRequest* request, ::memory_manager::AllocateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::AllocateRequest, ::memory_manager::AllocateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, std::move(f));
}

void MemoryManagerService::Stub::async::Create(::grpc::ClientContext* context, const ::memory_manager::AllocateRequest* request, ::memory_manager::AllocateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::AllocateResponse>* MemoryManagerService::Stub::PrepareAsyncCreateRaw(::grpc::ClientContext* context, const ::memory_manager::AllocateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::AllocateResponse, ::memory_manager::AllocateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Create_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::AllocateResponse>* MemoryManagerService::Stub::AsyncCreateRaw(::grpc::ClientContext* context, const ::memory_manager::AllocateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManagerService::Stub::IncreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest& request, ::memory_manager::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::ReferenceRequest, ::memory_manager::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IncreaseRefCount_, context, request, response);
}

void MemoryManagerService::Stub::async::IncreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest* request, ::memory_manager::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::ReferenceRequest, ::memory_manager::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IncreaseRefCount_, context, request, response, std::move(f));
}

void MemoryManagerService::Stub::async::IncreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest* request, ::memory_manager::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IncreaseRefCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::Empty>* MemoryManagerService::Stub::PrepareAsyncIncreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::Empty, ::memory_manager::ReferenceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IncreaseRefCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::Empty>* MemoryManagerService::Stub::AsyncIncreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIncreaseRefCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManagerService::Stub::DecreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest& request, ::memory_manager::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::ReferenceRequest, ::memory_manager::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DecreaseRefCount_, context, request, response);
}

void MemoryManagerService::Stub::async::DecreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest* request, ::memory_manager::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::ReferenceRequest, ::memory_manager::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecreaseRefCount_, context, request, response, std::move(f));
}

void MemoryManagerService::Stub::async::DecreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest* request, ::memory_manager::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecreaseRefCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::Empty>* MemoryManagerService::Stub::PrepareAsyncDecreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::Empty, ::memory_manager::ReferenceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DecreaseRefCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::Empty>* MemoryManagerService::Stub::AsyncDecreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::ReferenceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDecreaseRefCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManagerService::Stub::Set(::grpc::ClientContext* context, const ::memory_manager::SetRequest& request, ::memory_manager::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::SetRequest, ::memory_manager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void MemoryManagerService::Stub::async::Set(::grpc::ClientContext* context, const ::memory_manager::SetRequest* request, ::memory_manager::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::SetRequest, ::memory_manager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void MemoryManagerService::Stub::async::Set(::grpc::ClientContext* context, const ::memory_manager::SetRequest* request, ::memory_manager::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::SetResponse>* MemoryManagerService::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::memory_manager::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::SetResponse, ::memory_manager::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::SetResponse>* MemoryManagerService::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::memory_manager::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManagerService::Stub::Get(::grpc::ClientContext* context, const ::memory_manager::GetRequest& request, ::memory_manager::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::GetRequest, ::memory_manager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void MemoryManagerService::Stub::async::Get(::grpc::ClientContext* context, const ::memory_manager::GetRequest* request, ::memory_manager::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::GetRequest, ::memory_manager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void MemoryManagerService::Stub::async::Get(::grpc::ClientContext* context, const ::memory_manager::GetRequest* request, ::memory_manager::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::GetResponse>* MemoryManagerService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::memory_manager::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::GetResponse, ::memory_manager::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::GetResponse>* MemoryManagerService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::memory_manager::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

MemoryManagerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManagerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManagerService::Service, ::memory_manager::AllocateRequest, ::memory_manager::AllocateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::AllocateRequest* req,
             ::memory_manager::AllocateResponse* resp) {
               return service->Create(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManagerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManagerService::Service, ::memory_manager::ReferenceRequest, ::memory_manager::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::ReferenceRequest* req,
             ::memory_manager::Empty* resp) {
               return service->IncreaseRefCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManagerService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManagerService::Service, ::memory_manager::ReferenceRequest, ::memory_manager::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::ReferenceRequest* req,
             ::memory_manager::Empty* resp) {
               return service->DecreaseRefCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManagerService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManagerService::Service, ::memory_manager::SetRequest, ::memory_manager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::SetRequest* req,
             ::memory_manager::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManagerService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManagerService::Service, ::memory_manager::GetRequest, ::memory_manager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::GetRequest* req,
             ::memory_manager::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
}

MemoryManagerService::Service::~Service() {
}

::grpc::Status MemoryManagerService::Service::Create(::grpc::ServerContext* context, const ::memory_manager::AllocateRequest* request, ::memory_manager::AllocateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManagerService::Service::IncreaseRefCount(::grpc::ServerContext* context, const ::memory_manager::ReferenceRequest* request, ::memory_manager::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManagerService::Service::DecreaseRefCount(::grpc::ServerContext* context, const ::memory_manager::ReferenceRequest* request, ::memory_manager::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManagerService::Service::Set(::grpc::ServerContext* context, const ::memory_manager::SetRequest* request, ::memory_manager::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManagerService::Service::Get(::grpc::ServerContext* context, const ::memory_manager::GetRequest* request, ::memory_manager::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace memory_manager

